'use client';
import {useParams} from 'next/navigation';import {useEffect,useRef,useState} from 'react';import {Shell} from '@/components/Shell';import {Loading,ErrorNotice} from '@/components/States';import {api,stamp} from '@/lib/api';import {youtubeId} from '@/lib/youtube';
type Session={id:string;program_name:string;starts_at:string;ends_at:string;youtube_video_id:string|null;instructor:string|null};type Attendance={watched_seconds:number;qualified:boolean};
export default function Live(){const {id}=useParams<{id:string}>();const [session,setSession]=useState<Session|null>(null);const [attendance,setAttendance]=useState<Attendance|null>(null);const [error,setError]=useState('');const [now,setNow]=useState(Date.now());const active=useRef(false);
useEffect(()=>{api<Session>(`/sessions/${id}`).then(setSession).catch(e=>setError(e.message));const timer=setInterval(()=>setNow(Date.now()),1000);return()=>clearInterval(timer)},[id]);
useEffect(()=>{if(!attendance||!active.current)return;const timer=setInterval(()=>{api<Attendance>('/attendance/heartbeat',{method:'POST',body:JSON.stringify({sessionId:id,requestId:crypto.randomUUID()})}).then(setAttendance).catch(e=>setError(e.message));},60000);return()=>clearInterval(timer)},[attendance,id]);
async function join(){try{const state=await api<Attendance>('/attendance/start',{method:'POST',body:JSON.stringify({sessionId:id,requestId:crypto.randomUUID()})});active.current=true;setAttendance(state);}catch(e){setError((e as Error).message)}}
async function leave(){try{const state=await api<Attendance>('/attendance/complete',{method:'POST',body:JSON.stringify({sessionId:id,requestId:crypto.randomUUID()})});active.current=false;setAttendance(state);}catch(e){setError((e as Error).message)}}
const start=session?new Date(session.starts_at).getTime():0,end=session?new Date(session.ends_at).getTime():0;const before=now<start;const over=now>=end;const countdown=Math.max(0,Math.ceil((start-now)/60000));const videoId=youtubeId(session?.youtube_video_id);
return <Shell title={session?.program_name||'Live class'} subtitle="Breathe in. You’re right where you need to be.">{error&&<ErrorNotice message={error}/>} {!session&&!error?<Loading/>:session&&<div className="liveGrid"><section><div className="playerFrame">{attendance&&videoId?<iframe title="YouTube Live class" src={`https://www.youtube-nocookie.com/embed/${videoId}?autoplay=1`} allow="autoplay; encrypted-media; picture-in-picture" allowFullScreen/>:<div className="playerPlaceholder"><span>✺</span><h2>{attendance?'Your class is ready':'Your moment begins here'}</h2><p>{attendance?'Add a YouTube video ID or URL in .env to play the stream.':'Join the class to start tracking your attendance.'}</p></div>}</div><div className="liveActions">{before?<div className="countdown">Class begins in about {countdown} min</div>:over?<div className="countdown">This class has ended</div>:attendance?<button className="button outline" onClick={leave}>Leave class</button>:<button className="button primary" onClick={join}>Join live & track attendance →</button>}<span className={`attendanceBadge ${attendance?.qualified?'qualified':''}`}>{attendance?.qualified?'✓ Qualified attendance':attendance?`${Math.floor(attendance.watched_seconds/60)} minutes attended`:'Attendance starts when you join'}</span></div></section><aside className="panel liveSidebar"><span className="eyebrow">CLASS DETAILS</span><h2>{session.program_name}</h2><div className="detailRow"><span>When</span><strong>{stamp(session.starts_at)}</strong></div><div className="detailRow"><span>Instructor</span><strong>{session.instructor||'Appify instructor'}</strong></div><div className="detailRow"><span>Session</span><strong>{Math.round((end-start)/60000)} minutes</strong></div><div className="detailRow"><span>Attendance</span><strong>{attendance?.qualified?'Qualified':attendance?'In progress':'Not started'}</strong></div><div className="liveTip">✦ Keep this page open while you practice. We check in every minute and remember your progress if you reconnect.</div></aside></div>}</Shell>}
