'use client';
import {useCallback,useEffect,useState} from 'react';
import {api} from '@/lib/api';
type Asset={id:string;program_name:string;local_date:string;provider_type:string;provider_asset_id:string|null;provider_owned:boolean;asset_status:string;recording_status:string;deletion_status:string;delete_attempts:number;last_delete_error:string|null};
export function DailyAssetAdmin(){
 const [assets,setAssets]=useState<Asset[]>([]),[message,setMessage]=useState(''),[video,setVideo]=useState<Record<string,string>>({}),[owned,setOwned]=useState<Record<string,boolean>>({}),[ready,setReady]=useState<Record<string,boolean>>({});
 const load=useCallback(()=>api<Asset[]>('/admin/daily-assets').then(setAssets).catch(e=>setMessage(e.message)),[]);
 useEffect(()=>{load()},[load]);
 async function attach(a:Asset){try{await api(`/admin/daily-assets/${a.id}/provider`,{method:'PUT',body:JSON.stringify({providerType:'YOUTUBE',videoUrl:video[a.id]||'',providerOwned:!!owned[a.id],recordingReady:!!ready[a.id]})});setMessage('Asset saved.');load()}catch(e){setMessage((e as Error).message)}}
 async function action(a:Asset,kind:'ready'|'retry-delete'){try{await api(`/admin/daily-assets/${a.id}/${kind}`,{method:'POST'});setMessage('Asset updated.');load()}catch(e){setMessage((e as Error).message)}}
 return <section className="panel profileForm spaced"><span className="eyebrow">DAILY MEDIA</span><h2>Assets and cleanup</h2><p className="muted">Attach the source video for a date. Mark an archive ready after processing. Deletion applies only to assets explicitly marked as owned and programs with cleanup enabled.</p>{assets.slice(0,20).map(a=><div key={a.id} className="assetAdminRow"><strong>{a.program_name} · {a.local_date}</strong><small>{a.provider_type} · {a.asset_status} · Recording {a.recording_status} · Cleanup {a.deletion_status}{a.delete_attempts?` (${a.delete_attempts} attempts)`:''}</small><small>Provider ID: {a.provider_asset_id||'Not attached'}</small>{a.last_delete_error&&<small>Last error: {a.last_delete_error}</small>}{!a.provider_asset_id&&<><label>Video URL or ID<input value={video[a.id]||''} onChange={e=>setVideo(old=>({...old,[a.id]:e.target.value}))}/></label><label><input type="checkbox" checked={!!owned[a.id]} onChange={e=>setOwned(old=>({...old,[a.id]:e.target.checked}))}/> This account owns the provider asset</label><label><input type="checkbox" checked={!!ready[a.id]} onChange={e=>setReady(old=>({...old,[a.id]:e.target.checked}))}/> Archive ready for all slots</label><button className="button outline" onClick={()=>attach(a)}>Attach asset</button></>}{a.provider_asset_id&&a.asset_status==='PROCESSING'&&<button className="button outline" onClick={()=>action(a,'ready')}>Mark archive ready</button>}{a.deletion_status==='FAILED'&&<button className="button outline" onClick={()=>action(a,'retry-delete')}>Retry deletion</button>}</div>)}<button className="button outline" onClick={load}>Refresh assets</button>{message&&<p role="status" className="panelNote">{message}</p>}</section>
}
