'use client';
import {useEffect,useState} from 'react';
import {api} from '@/lib/api';
type Program={id:string;name:string};
type Slot={id?:string;localTime:string;enabled:boolean;instructorId?:string|null};
type Schedule={policy:{timezone:string;duration_minutes:number;join_early_minutes:number;close_late_minutes:number;cleanup_delay_minutes:number;cleanup_enabled:boolean;max_delete_attempts:number;source_series_id:string|null};slots:{id:string;local_time:string;enabled:boolean;instructor_id:string|null}[]};
export function ScheduleEditor({programs}:{programs:Program[]}){
 const [programId,setProgramId]=useState(''),[slots,setSlots]=useState<Slot[]>([]),[source,setSource]=useState(0),[timezone,setTimezone]=useState('Asia/Kolkata'),[duration,setDuration]=useState(45),[early,setEarly]=useState(5),[late,setLate]=useState(5),[cleanupDelay,setCleanupDelay]=useState(15),[cleanup,setCleanup]=useState(false),[maxAttempts,setMaxAttempts]=useState(5),[message,setMessage]=useState('');
 useEffect(()=>{if(!programId&&programs.length)setProgramId(programs[0].id)},[programId,programs]);
 useEffect(()=>{if(!programId)return;api<Schedule>(`/admin/programs/${programId}/schedule`).then(({policy,slots:rows})=>{setSlots(rows.map(r=>({id:r.id,localTime:r.local_time.slice(0,5),enabled:r.enabled,instructorId:r.instructor_id})));setSource(Math.max(0,rows.findIndex(r=>r.id===policy.source_series_id)));setTimezone(policy.timezone);setDuration(policy.duration_minutes);setEarly(policy.join_early_minutes);setLate(policy.close_late_minutes);setCleanupDelay(policy.cleanup_delay_minutes);setCleanup(policy.cleanup_enabled);setMaxAttempts(policy.max_delete_attempts);setMessage('')}).catch(e=>setMessage(e.message))},[programId]);
 function patch(index:number,change:Partial<Slot>){setSlots(old=>old.map((s,i)=>i===index?{...s,...change}:s))}
 function move(index:number,by:number){const next=[...slots],target=index+by;if(target<0||target>=next.length)return;[next[index],next[target]]=[next[target],next[index]];setSlots(next);if(source===index)setSource(target);else if(source===target)setSource(index)}
 async function save(){try{await api(`/admin/programs/${programId}/schedule`,{method:'PUT',body:JSON.stringify({timezone,durationMinutes:duration,joinEarlyMinutes:early,closeLateMinutes:late,cleanupDelayMinutes:cleanupDelay,cleanupEnabled:cleanup,maxDeleteAttempts:maxAttempts,sourceSlotIndex:source,slots})});setMessage('Saved. Changes to scheduled classes take effect tomorrow.');const fresh=await api<Schedule>(`/admin/programs/${programId}/schedule`);setSlots(fresh.slots.map(r=>({id:r.id,localTime:r.local_time.slice(0,5),enabled:r.enabled,instructorId:r.instructor_id}))) }catch(e){setMessage((e as Error).message)}}
 return <section className="panel profileForm spaced"><span className="eyebrow">DAILY SCHEDULE</span><h2>Class times</h2><p className="muted">Set the source class first. Later classes use the same day’s asset when it is ready. Schedule changes apply from tomorrow.</p><label>Program<select value={programId} onChange={e=>setProgramId(e.target.value)}>{programs.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label><div className="formTwo"><label>Timezone<input value={timezone} onChange={e=>setTimezone(e.target.value)} required/></label><label>Duration (minutes)<input type="number" min="1" max="360" value={duration} onChange={e=>setDuration(Number(e.target.value))}/></label><label>Join early (minutes)<input type="number" min="0" max="60" value={early} onChange={e=>setEarly(Number(e.target.value))}/></label><label>Close late (minutes)<input type="number" min="0" max="60" value={late} onChange={e=>setLate(Number(e.target.value))}/></label></div><div className="scheduleSlots">{slots.map((s,i)=><div className="scheduleSlot" key={s.id||`new-${i}`}><label>#{i+1}<input aria-label={`Slot ${i+1} time`} type="time" value={s.localTime} onChange={e=>patch(i,{localTime:e.target.value})}/></label><label><input type="checkbox" checked={s.enabled} onChange={e=>patch(i,{enabled:e.target.checked})}/> Enabled</label><label><input type="radio" name="sourceSlot" checked={source===i} onChange={()=>setSource(i)}/> Source</label><button type="button" className="button outline" onClick={()=>move(i,-1)} aria-label={`Move slot ${i+1} earlier`}>↑</button><button type="button" className="button outline" onClick={()=>move(i,1)} aria-label={`Move slot ${i+1} later`}>↓</button><button type="button" className="button outline" onClick={()=>{setSlots(old=>old.filter((_,j)=>j!==i));setSource(old=>old>i?old-1:Math.max(0,Math.min(old,slots.length-2)))}} aria-label={`Remove slot ${i+1}`}>Remove</button></div>)}</div><button type="button" className="button outline" onClick={()=>setSlots(old=>[...old,{localTime:'12:00',enabled:true}])}>Add time</button><div className="formTwo"><label><input type="checkbox" checked={cleanup} onChange={e=>setCleanup(e.target.checked)}/> Delete owned provider assets after expiry</label><label>Cleanup delay (minutes)<input type="number" min="0" max="1440" value={cleanupDelay} onChange={e=>setCleanupDelay(Number(e.target.value))}/></label><label>Maximum delete attempts<input type="number" min="1" max="20" value={maxAttempts} onChange={e=>setMaxAttempts(Number(e.target.value))}/></label></div><button type="button" className="button primary" onClick={save} disabled={!programId||!slots.length}>Save schedule</button>{message&&<p className="panelNote" role="status">{message}</p>}</section>;
}
