import {test,expect} from '@playwright/test';
test('member can sign in, see neutral class choices, and open a class',async({page})=>{
  const email=`member-browser-${Date.now()}@example.test`;
  await page.goto('/register');
  await page.getByLabel('Your name').fill('New Browser Member');
  await page.getByLabel('Email').fill(email);
  await page.getByLabel('Password').fill('DemoPass123!');
  await page.getByRole('button',{name:'Create account →'}).click();
  await page.locator('.programCard').filter({hasText:'Yoga Everyday'}).getByRole('button',{name:'Join program →'}).click();
  await page.getByRole('button',{name:'Sign out ↗'}).click();
  await page.goto('/login');
  await page.getByLabel('Email').fill(email);
  await page.getByLabel('Password').fill('DemoPass123!');
  await page.getByRole('button',{name:'Sign in →'}).click();
  await expect(page.getByRole('heading',{name:/Good day/})).toBeVisible();
  await expect(page.getByRole('link',{name:'Instructor view'})).toHaveCount(0);
  await expect(page.getByRole('link',{name:'Admin portal'})).toHaveCount(0);
  await expect(page.getByText('Yoga Everyday').first()).toBeVisible();
  expect(await page.locator('.classRow').count()).toBeGreaterThanOrEqual(6);
  await expect(page.getByText(/YouTube|Replay|Live class/i)).toHaveCount(0);
  await page.getByRole('link',{name:'View next class →'}).click();
  await expect(page.getByRole('heading',{name:'Yoga Everyday',level:1})).toBeVisible();
  await page.goto('/instructor');
  await expect(page.getByText('Instructor access is granted by an admin.')).toBeVisible();
});

test('admin creates a program and resets the form after saving',async({page})=>{
  await page.goto('/login');
  await page.getByLabel('Email').fill('admin@example.test');
  await page.getByLabel('Password').fill('DemoPass123!');
  await page.getByRole('button',{name:'Sign in →'}).click();
  await page.getByRole('link',{name:'Admin portal'}).click();
  const form=page.locator('form').filter({has:page.getByRole('heading',{name:'Create a program'})});
  const name=`Live E2E Test ${Date.now()}`;
  await form.getByLabel('Name',{exact:true}).fill(name);
  await form.getByLabel('Description').fill('Immediate local video testing.');
  await form.getByLabel('Duration (minutes)').fill('5');
  await form.getByRole('button',{name:'Create program'}).click();
  await expect(page.getByText(/Program created:/)).toBeVisible();
  await expect(form.getByLabel('Name',{exact:true})).toHaveValue('');
  await expect(form.getByLabel('Description')).toHaveValue('');
  await expect(page.locator('.errorCard')).toHaveCount(0);
  await page.goto('/programs');
  await expect(page.getByRole('heading',{name,exact:true})).toBeVisible();
});

test('admin publishes a library image through the web app',async({page})=>{
  await page.goto('/login');
  await page.getByLabel('Email').fill('admin@example.test');
  await page.getByLabel('Password').fill('DemoPass123!');
  await page.getByRole('button',{name:'Sign in →'}).click();
  await expect(page.getByRole('heading',{name:/Good day/})).toBeVisible();
  await expect(page.getByRole('link',{name:'Instructor view'})).toBeVisible();
  await expect(page.getByRole('link',{name:'Admin portal'})).toBeVisible();
  await page.goto('/admin');
  await expect(page.getByRole('heading',{name:'Class times'})).toBeVisible();
  const schedule=page.locator('section').filter({has:page.getByRole('heading',{name:'Class times'})});
  await schedule.getByLabel('Program').selectOption({label:'Yoga Everyday'});
  await expect(page.getByLabel('Slot 1 time')).toBeVisible();
  await expect(page.getByRole('heading',{name:'Assets and cleanup'})).toBeVisible();
  await expect(page.locator('.assetAdminRow').first()).toBeVisible();
  const title=`Browser article ${Date.now()}`;
  await page.getByLabel('Title').fill(title);
  await page.getByLabel('Body').fill('A small practice for today.');
  await page.getByLabel('Image (optional)').setInputFiles({name:'one.png',mimeType:'image/png',buffer:Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVQIHWP4z8DwHwAFgAI/ScL/nwAAAABJRU5ErkJggg==','base64')});
  const publishing=page.waitForResponse(response=>response.url().includes('/api/backend/admin/content')&&response.request().method()==='POST');
  await page.getByRole('button',{name:'Publish article'}).click();
  const published=await publishing;
  expect(published.status(),await published.text()).toBe(200);
  await expect(page.getByText(/Published:/)).toBeVisible();
  await expect(page.getByLabel('Title')).toHaveValue('');
  await expect(page.locator('.errorCard')).toHaveCount(0);
  await page.goto('/library');
  await expect(page.getByRole('heading',{name:title})).toBeVisible();
});

test('admin onboards a registered member as an instructor',async({page})=>{
  const email=`instructor-${Date.now()}@example.test`,password='DemoPass123!';
  await page.goto('/register');
  await page.getByLabel('Your name').fill('New Instructor');
  await page.getByLabel('Email').fill(email);
  await page.getByLabel('Password').fill(password);
  await page.getByRole('button',{name:'Create account →'}).click();
  await expect(page.getByRole('heading',{name:'Find your rhythm.',level:1})).toBeVisible();
  await expect(page.getByRole('link',{name:'Instructor view'})).toHaveCount(0);
  await page.getByRole('button',{name:'Sign out ↗'}).click();
  await page.goto('/login');
  await page.getByLabel('Email').fill('admin@example.test');
  await page.getByLabel('Password').fill(password);
  await page.getByRole('button',{name:'Sign in →'}).click();
  await expect(page.getByRole('link',{name:'Admin portal'})).toBeVisible();
  await page.getByRole('link',{name:'Admin portal'}).click();
  await page.getByLabel('Registered email').fill(email);
  await page.getByRole('button',{name:'Grant instructor access'}).click();
  await expect(page.getByText(`${email} can now sign in as an instructor.`)).toBeVisible();
  await expect(page.getByLabel('Registered email')).toHaveValue('');
  await expect(page.locator('.errorCard')).toHaveCount(0);
  await page.getByRole('button',{name:'Sign out ↗'}).click();
  await page.goto('/login');
  await page.getByLabel('Email').fill(email);
  await page.getByLabel('Password').fill(password);
  await page.getByRole('button',{name:'Sign in →'}).click();
  await expect(page.getByRole('link',{name:'Instructor view'})).toBeVisible();
  await expect(page.getByRole('link',{name:'Admin portal'})).toHaveCount(0);
  await page.getByRole('link',{name:'Instructor view'}).click();
  await expect(page.getByText('No classes are assigned yet.')).toBeVisible();
});

test('admin assigns the supplied YouTube Live link to a session',async({page})=>{
  await page.goto('/login');
  await page.getByLabel('Email').fill('admin@example.test');
  await page.getByLabel('Password').fill('DemoPass123!');
  await page.getByRole('button',{name:'Sign in →'}).click();
  await expect(page.getByRole('link',{name:'Admin portal'})).toBeVisible();
  await page.getByRole('link',{name:'Admin portal'}).click();
  const form=page.locator('form').filter({has:page.getByRole('heading',{name:'Create a live session'})});
  await form.getByLabel('Program').selectOption({label:'Yoga Everyday'});
  await form.getByLabel('Instructor').selectOption({label:'Asha Rao (instructor@example.test)'});
  await form.getByLabel('YouTube Live ID or URL').fill('https://www.youtube.com/live/GfvVuG5mXsA?si=MLqykU9yenqZaasW');
  await form.getByRole('button',{name:'Start test session now'}).click();
  const created=page.getByText(/Member class link:/);
  await expect(created).toBeVisible();
  await expect(form.getByLabel('YouTube Live ID or URL')).toHaveValue('');
  await expect(page.locator('.errorCard')).toHaveCount(0);
  const sessionId=(await created.textContent())?.match(/[0-9a-f-]{36}/)?.[0];
  expect(sessionId).toBeTruthy();
  await page.getByRole('button',{name:'Sign out ↗'}).click();
  await page.goto('/register');
  await page.getByLabel('Your name').fill('Playback Browser Member');
  await page.getByLabel('Email').fill(`playback-${Date.now()}@example.test`);
  await page.getByLabel('Password').fill('DemoPass123!');
  await page.getByRole('button',{name:'Create account →'}).click();
  await page.locator('.programCard').filter({hasText:'Yoga Everyday'}).getByRole('button',{name:'Join program →'}).click();
  await page.goto(`/live/${sessionId}`);
  const attendanceResponse=page.waitForResponse(response=>response.url().includes(`/api/backend/v1/session-slots/${sessionId}/join`));
  await page.getByRole('button',{name:'Enter class →'}).click();
  const started=await attendanceResponse;
  expect(started.status(),await started.text()).toBe(200);
  await expect(page.locator('iframe[title="Class player"]')).toBeVisible();
  await expect(page.getByText(/YouTube|Replay|Live class/i)).toHaveCount(0);
});

test('member reminder link survives sign in',async({page})=>{
  const email=`reminder-${Date.now()}@example.test`;
  await page.goto('/register');
  await page.getByLabel('Your name').fill('Reminder Member');
  await page.getByLabel('Email').fill(email);
  await page.getByLabel('Password').fill('DemoPass123!');
  await page.getByRole('button',{name:'Create account →'}).click();
  await page.locator('.programCard').filter({hasText:'Yoga Everyday'}).getByRole('button',{name:'Join program →'}).click();
  const link=await page.evaluate(async()=>{
    const slots=await fetch('/api/backend/sessions').then(r=>r.json());
    const slot=slots.find((s:{joinAvailability:string})=>['ALLOW','SESSION_NOT_OPEN','ASSET_NOT_READY'].includes(s.joinAvailability));
    if(!slot)throw new Error('No eligible future slot');
    const response=await fetch(`/api/backend/v1/join-links/${slot.slotId}`,{method:'POST'});
    if(!response.ok)throw new Error(await response.text());
    return {token:(await response.json()).token,slotId:slot.slotId};
  });
  await page.getByRole('button',{name:'Sign out ↗'}).click();
  await page.goto(`/j/${link.token}`);
  await expect(page).toHaveURL(/\/login\?next=/);
  await page.getByLabel('Email').fill(email);
  await page.getByLabel('Password').fill('DemoPass123!');
  await page.getByRole('button',{name:'Sign in →'}).click();
  await expect(page).toHaveURL(new RegExp(`/live/${link.slotId}$`));
});
